service: notes-api-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: MarkoRole
  region: eu-north-1
  iam:
    role: arn:aws:iam::228421314153:role/events-practice

plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  getNotes:
    handler: functions/getNotes/index.handler
    events:
      - httpApi:
          path: '/notes'
          method: GET
  postNotes:
    handler: functions/postNotes/index.handler
    events:
      - httpApi:
          path: '/notes'
          method: POST
  putNotes:
    handler: functions/changeNotes/index.handler
    events:
      - httpApi:
          path: '/notes'
          method: PUT
  deleteNotes:
    handler: functions/deleteNotes/index.handler
    events:
      - httpApi:
          path: '/notes'
          method: DELETE
  userSignup:
    handler: functions/userSignup/index.handler
    events:
      - httpApi:
          path: '/auth/signup'
          method: POST
  userLogin:
    handler: functions/userLogin/index.handler
    events:
      - httpApi:
          path: '/auth/login'
          method: POST

resources:
  Resources:
    notesDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'notes-db'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    usersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'notes-accounts'
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST